flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
	title = StringField("Title",
		validators=[DataRequired(), Length(max=100)])
	
	content = TextAreaField("Content",
		validators=[DataRequired()])

	submit = SubmitField("Post")

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
	return render_template("home.html", posts=posts)


@main.route("/about")
def about():
	return render_template("about.html", title="About")

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash("Your post has been created!", "success")
		return redirect(url_for('main.home'))
	return render_template("post_form.html", title="New Post", form=form)


@posts.route("/post/<int:post_id>")
def post_page(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template("post_page.html", title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash("Your post has been updated!", "success")
		return redirect(url_for('posts.post_page', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template("post_form.html", title="Update Post", form=form)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash("Your post has been deleted!", "success")
	return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
	RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Your account has been created! You are now able to log in.', 'success')
		return redirect(url_for('users.login'))
	return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash("Login failed. Please check your email and password.", 'danger')
	return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated!', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template("account.html", title="Account", image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
	.order_by(Post.date_posted.desc())\
	.paginate(per_page=5, page=page)
	return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash("That is an invalid or expired token.", "warning")
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Your password has been updated! You are now able to log in.', 'success')
		return redirect(url_for('users.login'))
	return render_template("reset_token.html", title="Reset Password", form=form)

flaskblog/templates/about.html
{% extends 'layout.html' %}
{% block body %}
<h1>Yo</h1>
{% endblock body %}

flaskblog/templates/account.html
{% extends 'layout.html' %}
	{% block body %}
	<div class="card p-3">
		<div class="d-flex flex-row">
			<div class="pb-3 pe-3">
				<img class="profile-pic" src="{{ image_file }}">
			</div>
			<div>
				<p class="fs-3 mb-0">
					{{ current_user.username }}
				</p>
				<small class="text-muted">
					{{ current_user.email }}
				</small>
			</div>
		</div>

		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset>
				<legend>
					Update info
				</legend>
				<!-- username -->
				<div class="mb-2">
					{{ form.username.label(class="form-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control") }}
					{% endif %}
				</div>
				<!-- email -->
				<div class="mb-2">
					{{ form.email.label(class="form-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control") }}
					{% endif %}
				</div>
				<!-- picture -->
				<div class="mb-2">
					{{ form.picture.label }}
					{{ form.picture(class="form-control") }}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span><br>
						{% endfor %}
					{% endif %}
				</div>
				<!-- submit button -->
				<div class="mt-3">
					{{ form.submit(class="btn btn-outline-primary") }}
				</div>
			</fieldset>
		</form>
	</div>
	{% endblock body %}

flaskblog/templates/home.html
{% extends 'layout.html' %}
	{% block body %}
		{% for post in posts.items %}
		<div class="card d-flex flex-row p-2 mb-3">
			<img class="profile-pic" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
			<div class="ms-3 flex-fill">
				<a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="text-primary mb-0 fs-6 d-inline anchor">
					{{ post.author.username }}
				</a>
					&nbsp; &nbsp;
				<small class="text-muted d-inline">
					{{ post.date_posted.strftime('%d-%m-%Y') }}
				</small>
				<hr class="m-0 mt-1 bg-grey">
				<a class="card-title fs-3 anchor text-dark" id="home-post-title" 
					href="{{ url_for('posts.post_page', post_id=post.id) }}">
					{{ post.title }}
				</a>
				<p class="card-text fs-5 my-2" id="home-post-content">
					{{ post.content }}
				</p>
			</div>
		</div>
		{% endfor %}

		{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
			{% if page_num %}
				{% if posts.page == page_num %}
					<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">
					{{ page_num }}</a>
				{% else %}
					<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">
					{{ page_num }}</a>
				{% endif %}
			{% else %}
				...
			{% endif %}
		{% endfor %}
	{% endblock body %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">


	{% if title %}
		<title>Flask Blog - {{ title }}</title>
	{% else %}
		<title>Flask Blog</title>
	{% endif %}
</head>
<body>
	<div id="navbar-space-filler"></div>

	<nav class="navbar navbar-expand-lg navbar-light bg-grey fixed-top">
		<div class="container">
			<a class="navbar-brand fs-3" href="#">Flask Blog</a>

			<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#logmenu">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse ms-4" id="logmenu">
				<ul class="navbar-nav fs-5">
					<li class="nav-item">
						<a href="{{ url_for('main.home') }}" class="nav-link">Home</a>
					</li>
					<li class="nav-item">
						<a href="{{ url_for('main.about') }}" class="nav-link">About</a>
					</li>
				</ul>
				<ul class="navbar-nav ms-auto fs-5">
					{% if current_user.is_authenticated %}
						<li class="nav-item">
							<a href="{{ url_for('posts.new_post') }}" class="nav-link">
							New Post</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('users.account') }}" class="nav-link">
							Account</a>
						</li>
						<li class="nav-item">
							<a href="#" class="nav-link"
							data-bs-toggle="modal" data-bs-target="#LogoutModal">
							Logout</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a href="{{ url_for('users.login') }}" class="nav-link">Login</a>
						</li>
						<li class="nav-item">
							<a href="{{ url_for('users.register') }}" class="nav-link">Register</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<!-- Modal -->
	<div class="modal fade" id="LogoutModal" tabindex="-1">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title">Confirm Logout</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	        <a href="{{ url_for('users.logout') }}" class="btn btn-primary">Logout</a>
	      </div>
	    </div>
	  </div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-lg-8">

				{% with messages = get_flashed_messages(with_categories=true) %}
				 {% if messages %}
				  {% for category, message in messages %}
				  <div class="alert alert-{{ category }}">
				  	{{ message }}
				  </div>
				  {% endfor %}
				 {% endif %}
				{% endwith %}

			{% block body %}{% endblock body %}
			</div>
			<div class="col-lg-4 d-lg-inline-block" id="sidebar">
				<div class="card p-3">
					<p class="card-title fs-3">
						Our Sidebar
					</p>
					<p class="card-text">
						You can put any information here you'd like.
					</p>
					<div class="card">
						<ul class="list-group list-group-flush">
							<li class="list-group-item">Latest Posts</li>
							<li class="list-group-item">Announcements</li>
							<li class="list-group-item">Calendars</li>
							<li class="list-group-item">etc</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block body %}
	<div class="card p-3 pt-2">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset>
				<legend>
					Log In
				</legend>
				<!-- email -->
				<div class="mb-2">
					{{ form.email.label(class="form-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control") }}
					{% endif %}
				</div>
				<!-- password -->
				<div class="mb-2">
					{{ form.password.label(class="form-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control") }}
					{% endif %}
				</div>
				<!-- remember me -->
				<div class="form-check">
					{{ form.remember(class='form-check-input') }}
					{{ form.remember.label(class='form-check-label') }}
				</div>
				<!-- submit button -->
				<div class="my-3">
					{{ form.submit(class="btn btn-outline-primary") }}
				</div>
				<small class="text-muted">
					<a href="{{ url_for('users.reset_request') }}" class="anchor">
						Forgot Password?
					</a>
				</small>
			</fieldset>
		</form>
	</div>
	<div class="px-3 pt-2">
		<p class="text-muted">
			<small>Need an account?
				<a class="anchor" href="{{ url_for('users.register') }}">Sign Up</a>
			</small>
		</p>
	</div>
{% endblock body %}

flaskblog/templates/post_form.html
{% extends 'layout.html' %}
{% block body %}
	<div class="card p-3 pt-2">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset>
				<legend>
					{{ title }}
				</legend>
				<!-- title -->
				<div class="mb-2">
					{{ form.title.label(class="form-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control") }}
					{% endif %}
				</div>
				<!-- content -->
				<div class="mb-2">
					{{ form.content.label(class="form-label") }}
					{% if form.content.errors %}
						{{ form.content(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.content.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.content(class="form-control") }}
					{% endif %}
				</div>
				<!-- submit button -->
				<div class="mt-3">
					{{ form.submit(class="btn btn-outline-primary") }}
				</div>
			</fieldset>
		</form>
	</div>
{% endblock body %}

flaskblog/templates/post_page.html
{% extends 'layout.html' %}
{% block body %}
	<div class="card d-flex flex-row p-2 mb-3">
		<img class="profile-pic" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
		<div class="ms-3 flex-fill">
			<span class="d-flex flex-row">
				<a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="text-primary mb-0 fs-6 d-inline anchor">
					{{ post.author.username }}
				</a>
					&nbsp; &nbsp;
				<small class="text-muted d-inline">
					{{ post.date_posted.strftime('%d-%m-%Y') }}
				</small>
				{% if post.author == current_user %}
					<div class="d-inline ms-auto">
						<a class="btn btn-primary btn-sm mx-2" 
						href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
						<button type="button" class="btn btn-danger btn-sm"
							 data-bs-toggle="modal" data-bs-target="#DeleteModal">
							Delete
						</button>
					</div>
				{% endif %}
			</span>
			<hr class="m-0 mt-1 bg-grey">
			<p class="card-title fs-3">
				{{ post.title }}
			</p>
			<p class="card-text fs-5">
				{{ post.content }}
			</p>
		</div>
	</div>
	<!-- Modal -->
	<div class="modal fade" id="DeleteModal" tabindex="-1">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title">Delete Post?</h5>
	        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
	        	<input type="submit" value="Delete" class="btn btn-danger">
	        </form>
	      </div>
	    </div>
	  </div>
	</div>

{% endblock body %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block body %}
	<div class="card p-3 pt-2">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset>
				<legend>
					Join Today
				</legend>
				<!-- username -->
				<div class="mb-2">
					{{ form.username.label(class="form-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control") }}
					{% endif %}
				</div>
				<!-- email -->
				<div class="mb-2">
					{{ form.email.label(class="form-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control") }}
					{% endif %}
				</div>
				<!-- password -->
				<div class="mb-2">
					{{ form.password.label(class="form-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control") }}
					{% endif %}
				</div>
				<!-- confirm password -->
				<div class="mb-2">
					{{ form.confirm_password.label(class="form-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control") }}
					{% endif %}
				</div>
				<!-- submit button -->
				<div class="mt-3">
					{{ form.submit(class="btn btn-outline-primary") }}
				</div>
			</fieldset>
		</form>
	</div>
	<div class="px-3 pt-2">
		<p class="text-muted">
			<small>Already have an account?
				<a class="anchor" href="{{ url_for('users.login') }}">Login</a>
			</small>
		</p>
	</div>
{% endblock body %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block body %}
	<div class="card p-3 pt-2">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset>
				<legend>
					Reset Password
				</legend>
				<!-- email -->
				<div class="mb-2">
					{{ form.email.label(class="form-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control") }}
					{% endif %}
				</div>
				<!-- submit button -->
				<div class="my-3">
					{{ form.submit(class="btn btn-outline-primary") }}
				</div>
			</fieldset>
		</form>
	</div>
{% endblock body %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}
{% block body %}
	<div class="card p-3 pt-2">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset>
				<legend>
					Reset Password
				</legend>
				<!-- password -->
				<div class="mb-2">
					{{ form.password.label(class="form-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control") }}
					{% endif %}
				</div>
				<!-- confirm password -->
				<div class="mb-2">
					{{ form.confirm_password.label(class="form-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control") }}
					{% endif %}
				</div>
				<!-- submit button -->
				<div class="my-3">
					{{ form.submit(class="btn btn-outline-primary") }}
				</div>
			</fieldset>
		</form>
	</div>
{% endblock body %}

flaskblog/templates/user_posts.html
{% extends 'layout.html' %}
	{% block body %}
		<div class="mb-2">
			<img class="profile-pic me-2"
				src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
			<p class="fs-2 d-inline">Posts from {{ user.username }}({{ posts.total }})</p>
		</div>
		{% for post in posts.items %}
		<div class="card p-3 mb-3">
			<small class="text-muted d-inline">
				{{ post.date_posted.strftime('%d-%m-%Y') }}
			</small>
			<hr class="m-0 mt-1 bg-grey">
			<a class="card-title fs-3 anchor text-dark" 
				href="{{ url_for('posts.post_page', post_id=post.id) }}">
				{{ post.title }}
			</a>
			<p class="card-text fs-5 my-2">
				{{ post.content }}
			</p>
		</div>
		{% endfor %}

		{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=3) %}
			{% if page_num %}
				{% if posts.page == page_num %}
					<a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">
					{{ page_num }}</a>
				{% else %}
					<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">
					{{ page_num }}</a>
				{% endif %}
			{% else %}
				...
			{% endif %}
		{% endfor %}
	{% endblock body %}